language: node_js
node_js:
  - 4.6.0
services: 
  - sqlite
matrix:
  fast_finish: true
  allow_failures:
  - node_js: 5.12.0
after_success:
  - ./scripts/deploy.sh
before_install:
  - npm install -g sqlite3
env:
  - CXX=g++-4.8