language: node_js
sudo: required
node_js:
  - 4.6.0
sudo: required
services: 
  - sqlite3
matrix:
  fast_finish: true
  allow_failures:
  - node_js: 5.12.0
after_success:
  - sh ./scripts/deploy.sh
before_install:
  - npm install -g sqlite3
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.8
env:
  - CXX=g++-4.8
