language: node_js
sudo: required
node_js:
  - 4.6.0
sudo: required
services: 
  - sqlite
matrix:
  fast_finish: true
  allow_failures:
  - node_js: 5.12.0
after_success:
  - ./scripts/deploy.sh
before_install:
  - npm install -g sqlite3
  - openssl aes-256-cbc -K $encrypted_3bd1f7d0b101_key -iv $encrypted_3bd1f7d0b101_iv
  -in client-secret.json.enc -out client-secret.json -d
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.8
env:
  - CXX=g++-4.8
